/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import DTO.ClienteDTO;
import DTO.FechasDTO;
import DTO.MesaDTO;
import DTO.ReservaDTO;
import DTO.RestauranteDTO;
import Excepcion.NegocioException;
import InterfacesNegocio.IClienteNegocio;
import InterfacesNegocio.IMesaNegocio;
import InterfacesNegocio.IReservaNegocio;
import InterfacesNegocio.IRestauranteNegocio;
import Negocio.ClienteNegocio;
import Negocio.MesaNegocio;
import Negocio.ReservaNegocio;
import Negocio.RestauranteNegocio;
import com.github.lgooddatepicker.components.DateTimePicker;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author santi
 */
public class FramePorArea extends javax.swing.JFrame {

    FrameModuloConsultas frmModuloConsultas;
    JComboBox boxSeccion;
    JComboBox boxTipoDeMesa;
    DateTimePicker pickerFechaYHoraDesde;
    DateTimePicker pickerFechaYHoraHasta;
    
    IRestauranteNegocio restauranteNegocio = new RestauranteNegocio();
    IReservaNegocio reservaNegocio = new ReservaNegocio();
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePorArea(FrameModuloConsultas frmModuloConsultas) {

        this.frmModuloConsultas = frmModuloConsultas;
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        inicializarComponentes();
        
        lblVerDetalles.setVisible(false);
        lblTipoSeleccionado.setVisible(false);
        
    }
    
    public void inicializarComponentes(){
    
 
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        lblPorTipoDeMesa = new javax.swing.JLabel();
        lblPorSeccion = new javax.swing.JLabel();
        panelFiltro = new javax.swing.JPanel();
        lblVerDetalles = new javax.swing.JLabel();
        lblTipoSeleccionado = new javax.swing.JLabel();
        panelFiltroFecha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(51, 36, 12));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes por cliente.png"))); // NOI18N

        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/X.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/(-.png"))); // NOI18N
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        lblPorTipoDeMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorTipoDeMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Por Tipo de Mesa.png"))); // NOI18N
        lblPorTipoDeMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPorTipoDeMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPorTipoDeMesaMouseClicked(evt);
            }
        });

        lblPorSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Por Sección.png"))); // NOI18N
        lblPorSeccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPorSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPorSeccionMouseClicked(evt);
            }
        });

        panelFiltro.setBackground(new java.awt.Color(51, 36, 12));

        lblVerDetalles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ver Detalles.png"))); // NOI18N
        lblVerDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerDetallesMouseClicked(evt);
            }
        });

        lblTipoSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes por cliente.png"))); // NOI18N

        panelFiltroFecha.setBackground(new java.awt.Color(51, 36, 12));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblPorSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorTipoDeMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCerrar))
                            .addComponent(lblTipoSeleccionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                            .addComponent(lblVerDetalles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCerrar)
                    .addComponent(lblAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo)
                .addGap(24, 24, 24)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPorTipoDeMesa)
                    .addComponent(lblPorSeccion))
                .addGap(78, 78, 78)
                .addComponent(lblTipoSeleccionado)
                .addGap(14, 14, 14)
                .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblVerDetalles)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        // TODO add your handling code here:
        frmModuloConsultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void llenarPickers(){
    
        pickerFechaYHoraDesde = new DateTimePicker();
        pickerFechaYHoraHasta = new DateTimePicker();
        
        Icon iconDesde = new ImageIcon(getClass().getResource("/Desde.png"));
        JLabel lblDesde = new JLabel(iconDesde);
        
        Icon iconHasta = new ImageIcon(getClass().getResource("/Hasta.png"));
        JLabel lblHasta = new JLabel(iconHasta);
        
        Icon iconLabel = new ImageIcon(getClass().getResource("/Fecha.png"));
        lblTipoSeleccionado.setIcon(iconLabel);
        lblTipoSeleccionado.setVisible(true);
        
        panelFiltroFecha.setLayout(new FlowLayout());
        panelFiltroFecha.removeAll();
        panelFiltroFecha.add(lblDesde);
        panelFiltroFecha.add(pickerFechaYHoraDesde);
        panelFiltroFecha.add(lblHasta);
        panelFiltroFecha.add(pickerFechaYHoraHasta);  
        
    }
    private void lblPorTipoDeMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPorTipoDeMesaMouseClicked
        // TODO add your handling code here:

        boxSeccion = null;
        boxTipoDeMesa = new JComboBox();
        Icon iconLabel = new ImageIcon(getClass().getResource("/Tipo de mesa.png"));
        lblTipoSeleccionado.setIcon(iconLabel);
        lblTipoSeleccionado.setVisible(true);
        
        
        panelFiltro.setLayout(new GridLayout());
        panelFiltro.removeAll();
        
        boxTipoDeMesa.addItem("Pequeña");
        boxTipoDeMesa.addItem("Mediana");
        boxTipoDeMesa.addItem("Grande");
        
        panelFiltro.add(boxTipoDeMesa);
        Dimension dimensiones = new Dimension(304, 54);
        panelFiltro.setPreferredSize(dimensiones);
        
        llenarPickers();
        
        this.revalidate();
        this.repaint();
        
        lblVerDetalles.setVisible(true);
        
    }//GEN-LAST:event_lblPorTipoDeMesaMouseClicked

    
    public void llenarComboSecciones(){
        
        try {
            for(String ubicacion : restauranteNegocio.buscarRestaurante().getUbicaciones()){
                
                boxSeccion.addItem(ubicacion);
                
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al llenar box de secciones" + ex);
        }
        
    }
    
    private void lblPorSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPorSeccionMouseClicked
        // TODO add your handling code here:
        boxSeccion = new JComboBox();
        boxTipoDeMesa = null;
        pickerFechaYHoraDesde = null;
        pickerFechaYHoraHasta = null;   
        
        Icon iconLabel = new ImageIcon(getClass().getResource("/Sección.png"));
        lblTipoSeleccionado.setIcon(iconLabel);
        lblTipoSeleccionado.setVisible(true);
        
        
        panelFiltro.setLayout(new GridLayout());
        panelFiltro.removeAll();
        
        llenarComboSecciones();
        
        panelFiltro.add(boxSeccion);      
        Dimension dimensiones = new Dimension(304, 54);
        panelFiltro.setPreferredSize(dimensiones);
        
        llenarPickers();
        
        this.revalidate();
        this.repaint();
        
        lblVerDetalles.setVisible(true);
        

    }//GEN-LAST:event_lblPorSeccionMouseClicked


    public boolean pasaVerificacionesFecha(){
    
        if(pickerFechaYHoraDesde.getDateTimePermissive() == null){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha y hora de inicio");
            return false;
        }
    
        if(pickerFechaYHoraHasta.getDateTimePermissive() == null){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha y hora de final");
            return false;
        }
    
        if(pickerFechaYHoraHasta.getDateTimePermissive().isBefore(pickerFechaYHoraDesde.getDateTimePermissive())){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha y hora final que sea después de la inicial");
            return false;
        }
    
        if(pickerFechaYHoraDesde.getDateTimePermissive().isAfter(pickerFechaYHoraHasta.getDateTimePermissive())){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha y hora inicial que sea antes de la final");
            return false;
        }
        
        return true;
        
    }
    
    private void lblVerDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerDetallesMouseClicked
        // TODO add your handling code here:
        
        if(!pasaVerificacionesFecha())
            return;
        
        if(boxSeccion != null){

            LocalDateTime desdeAux = pickerFechaYHoraDesde.getDateTimePermissive();
            ZonedDateTime zonedDateTimeD = desdeAux.atZone(ZoneId.systemDefault());
            Date dateD = Date.from(zonedDateTimeD.toInstant());
            Calendar desde = Calendar.getInstance();
            desde.setTime(dateD);

            LocalDateTime hastaAux = pickerFechaYHoraHasta.getDateTimePermissive();
            ZonedDateTime zonedDateTimeH = hastaAux.atZone(ZoneId.systemDefault());
            Date dateH = Date.from(zonedDateTimeH.toInstant());
            Calendar hasta = Calendar.getInstance();
            hasta.setTime(dateH);
                
            FechasDTO fechas = new FechasDTO(desde, hasta);
            
            ReservaDTO seccion = new ReservaDTO();
            seccion.setSeccion(boxSeccion.getSelectedItem().toString());
            
            try {
                FrameReporte frm = new FrameReporte(this, reservaNegocio.buscarReservasPorSeccion(seccion, fechas), boxSeccion.getSelectedItem().toString());
                frm.setVisible(true);
                this.dispose();
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, "Error al buscar con estos filtros" + ex);
            }
               
        }
        
        if(boxTipoDeMesa != null){

            LocalDateTime desdeAux = pickerFechaYHoraDesde.getDateTimePermissive();
            ZonedDateTime zonedDateTimeD = desdeAux.atZone(ZoneId.systemDefault());
            Date dateD = Date.from(zonedDateTimeD.toInstant());
            Calendar desde = Calendar.getInstance();
            desde.setTime(dateD);

            LocalDateTime hastaAux = pickerFechaYHoraHasta.getDateTimePermissive();
            ZonedDateTime zonedDateTimeH = hastaAux.atZone(ZoneId.systemDefault());
            Date dateH = Date.from(zonedDateTimeH.toInstant());
            Calendar hasta = Calendar.getInstance();
            hasta.setTime(dateH);
                
            FechasDTO fechas = new FechasDTO(desde, hasta);
            
            ReservaDTO seccion = new ReservaDTO();
            String titulo = "error";
            
            
            if(boxTipoDeMesa.getSelectedItem().toString().equals("Pequeña")){
                titulo = "Pequeña";
                seccion.setNumPersonas(2);
            }
            
            if(boxTipoDeMesa.getSelectedItem().toString().equals("Mediana")){
                titulo = "Mediana";
                seccion.setNumPersonas(4);
            }
            
            if(boxTipoDeMesa.getSelectedItem().toString().equals("Grande")){
                titulo = "Grande";
                seccion.setNumPersonas(8);
            }

            
            try {
                FrameReporte frm = new FrameReporte(this, reservaNegocio.buscarReservasPorTipo(seccion, fechas), titulo);
                frm.setVisible(true);
                this.dispose();
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, "Error al buscar con estos filtros" + ex);
            }
               
        }
                
    }//GEN-LAST:event_lblVerDetallesMouseClicked


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPorSeccion;
    private javax.swing.JLabel lblPorTipoDeMesa;
    private javax.swing.JLabel lblTipoSeleccionado;
    private javax.swing.JLabel lblVerDetalles;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelFiltroFecha;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
