/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import DTO.ClienteDTO;
import DTO.MesaDTO;
import DTO.ReservaDTO;
import DTO.RestauranteDTO;
import Excepcion.NegocioException;
import InterfacesNegocio.IClienteNegocio;
import InterfacesNegocio.IMesaNegocio;
import InterfacesNegocio.IRestauranteNegocio;
import Negocio.ClienteNegocio;
import Negocio.MesaNegocio;
import Negocio.RestauranteNegocio;
import com.github.lgooddatepicker.components.DateTimePicker;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author santi
 */
public class FramePorArea extends javax.swing.JFrame {

    FrameModuloConsultas frmModuloConsultas;
    JTextField fldTelefono;
    JTextField fldNombre;
    DateTimePicker pickerFechaYHoraDesde;
    DateTimePicker pickerFechaYHoraHasta;
    
    IClienteNegocio clienteNegocio = new ClienteNegocio();
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePorArea(FrameModuloConsultas frmModuloConsultas) {

        this.frmModuloConsultas = frmModuloConsultas;
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        inicializarComponentes();
        
        lblGenerarReporte.setVisible(false);
        lblTipoSeleccionado.setVisible(false);
        
    }
    
    public void inicializarComponentes(){
    
 
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        lblPorTelefono = new javax.swing.JLabel();
        lblPorNombre = new javax.swing.JLabel();
        lblPorFecha = new javax.swing.JLabel();
        panelFiltro = new javax.swing.JPanel();
        lblGenerarReporte = new javax.swing.JLabel();
        lblTipoSeleccionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(51, 36, 12));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes por cliente.png"))); // NOI18N

        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/X.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/(-.png"))); // NOI18N
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        lblPorTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Por Teléfono.png"))); // NOI18N
        lblPorTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPorTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPorTelefonoMouseClicked(evt);
            }
        });

        lblPorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Por Nombre.png"))); // NOI18N
        lblPorNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPorNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPorNombreMouseClicked(evt);
            }
        });

        lblPorFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Por Fecha.png"))); // NOI18N
        lblPorFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPorFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPorFechaMouseClicked(evt);
            }
        });

        panelFiltro.setBackground(new java.awt.Color(51, 36, 12));

        lblGenerarReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Generar reporte.png"))); // NOI18N
        lblGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerarReporteMouseClicked(evt);
            }
        });

        lblTipoSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes por cliente.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(lblPorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblPorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCerrar))
                            .addComponent(lblTipoSeleccionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCerrar)
                    .addComponent(lblAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo)
                .addGap(24, 24, 24)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPorTelefono)
                    .addComponent(lblPorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorFecha)
                .addGap(18, 18, 18)
                .addComponent(lblTipoSeleccionado)
                .addGap(14, 14, 14)
                .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(lblGenerarReporte)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        // TODO add your handling code here:
        frmModuloConsultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblPorTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPorTelefonoMouseClicked
        // TODO add your handling code here:
        fldTelefono = new JTextField();
        fldNombre = null;
        pickerFechaYHoraDesde = null;
        pickerFechaYHoraHasta = null;   
        
        Icon iconLabel = new ImageIcon(getClass().getResource("/Teléfono.png"));
        lblTipoSeleccionado.setIcon(iconLabel);
        lblTipoSeleccionado.setVisible(true);
        
        
        panelFiltro.setLayout(new GridLayout());
        panelFiltro.removeAll();
        panelFiltro.add(fldTelefono);      
        Dimension dimensiones = new Dimension(304, 54);
        panelFiltro.setPreferredSize(dimensiones);
        
        this.revalidate();
        this.repaint();
        
        lblGenerarReporte.setVisible(true);
        
    }//GEN-LAST:event_lblPorTelefonoMouseClicked

    private void lblPorNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPorNombreMouseClicked
        // TODO add your handling code here:
        fldTelefono = null;
        fldNombre = new JTextField();
        pickerFechaYHoraDesde = null;
        pickerFechaYHoraHasta = null;      
        
        Icon iconLabel = new ImageIcon(getClass().getResource("/Nombre.png"));
        lblTipoSeleccionado.setIcon(iconLabel);
        lblTipoSeleccionado.setVisible(true);
        
        
        panelFiltro.setLayout(new GridLayout());
        panelFiltro.removeAll();
        panelFiltro.add(fldNombre);
        Dimension dimensiones = new Dimension(304, 54);
        panelFiltro.setPreferredSize(dimensiones);
        
        this.revalidate();
        this.repaint();
        
        lblGenerarReporte.setVisible(true);
        
    }//GEN-LAST:event_lblPorNombreMouseClicked

    private void lblPorFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPorFechaMouseClicked
        // TODO add your handling code here:
        fldTelefono = null;
        fldNombre = null;
        pickerFechaYHoraDesde = new DateTimePicker();
        pickerFechaYHoraHasta = new DateTimePicker();
        
        Icon iconDesde = new ImageIcon(getClass().getResource("/Desde.png"));
        JLabel lblDesde = new JLabel(iconDesde);
        
        Icon iconHasta = new ImageIcon(getClass().getResource("/Hasta.png"));
        JLabel lblHasta = new JLabel(iconHasta);
        
        Icon iconLabel = new ImageIcon(getClass().getResource("/Fecha.png"));
        lblTipoSeleccionado.setIcon(iconLabel);
        lblTipoSeleccionado.setVisible(true);
        
        panelFiltro.setLayout(new FlowLayout());
        panelFiltro.removeAll();
        panelFiltro.add(lblDesde);
        panelFiltro.add(pickerFechaYHoraDesde);
        panelFiltro.add(lblHasta);
        panelFiltro.add(pickerFechaYHoraHasta);  
        Dimension dimensiones = new Dimension(304, 108);
        panelFiltro.setPreferredSize(dimensiones);
        
        this.revalidate();
        this.repaint();
        
        lblGenerarReporte.setVisible(true);
        
    }//GEN-LAST:event_lblPorFechaMouseClicked


    
    private void lblGenerarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarReporteMouseClicked
        // TODO add your handling code here:
           
                
    }//GEN-LAST:event_lblGenerarReporteMouseClicked


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblGenerarReporte;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPorFecha;
    private javax.swing.JLabel lblPorNombre;
    private javax.swing.JLabel lblPorTelefono;
    private javax.swing.JLabel lblTipoSeleccionado;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
