/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import DTO.MesaDTO;
import DTO.MesasAGuardarDTO;
import DTO.ReservaDTO;
import DTO.RestauranteDTO;
import Excepcion.NegocioException;
import InterfacesNegocio.IMesaNegocio;
import InterfacesNegocio.IRestauranteNegocio;
import Negocio.MesaNegocio;
import Negocio.RestauranteNegocio;
import com.github.lgooddatepicker.components.DateTimePicker;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author santi
 */
public class FrameInsertarMesas extends javax.swing.JFrame {

    FrameModuloMesas frmModulo;
    IRestauranteNegocio restauranteNegocio = new RestauranteNegocio();
    IMesaNegocio mesaNegocio = new MesaNegocio();
    
    /**
     * Creates new form FramePrincipal
     */
    public FrameInsertarMesas(FrameModuloMesas frmModulo) {

        this.frmModulo = frmModulo;
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();

        
        inicializarComponentes();
        
    }
    
    public void inicializarComponentes(){
    
        llenarComboSecciones();
        
    }
    
    public void llenarComboSecciones(){
        
        try {
            for(String ubicacion : restauranteNegocio.buscarRestaurante().getUbicaciones()){
                
                boxSeccion.addItem(ubicacion);
                
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al llenar box de secciones" + ex);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        boxSeccion = new javax.swing.JComboBox<>();
        lblSeccion = new javax.swing.JLabel();
        boxCantidadPequeñas = new javax.swing.JComboBox<>();
        lblComensales = new javax.swing.JLabel();
        lblComensales1 = new javax.swing.JLabel();
        boxCantidadMedianas = new javax.swing.JComboBox<>();
        lblComensales2 = new javax.swing.JLabel();
        boxCantidadGrandes = new javax.swing.JComboBox<>();
        lblInsertar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(51, 36, 12));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Módulo de mesa.png"))); // NOI18N

        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/X.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/(-.png"))); // NOI18N
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        boxSeccion.setBackground(new java.awt.Color(241, 228, 153));
        boxSeccion.setForeground(new java.awt.Color(0, 0, 0));

        lblSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Seleccion la seccion deseada.png"))); // NOI18N

        boxCantidadPequeñas.setBorder(new LineBorder(new Color(221,188,0)));
        boxCantidadPequeñas.setBackground(new java.awt.Color(255,243,163));
        boxCantidadPequeñas.setBackground(new java.awt.Color(241, 228, 153));
        boxCantidadPequeñas.setForeground(new java.awt.Color(0, 0, 0));
        boxCantidadPequeñas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblComensales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComensales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cantidad de pequeñas.png"))); // NOI18N

        lblComensales1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComensales1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cantidad de medianas.png"))); // NOI18N

        boxCantidadMedianas.setBorder(new LineBorder(new Color(221,188,0)));
        boxCantidadMedianas.setBackground(new java.awt.Color(255,243,163));
        boxCantidadMedianas.setBackground(new java.awt.Color(241, 228, 153));
        boxCantidadMedianas.setForeground(new java.awt.Color(0, 0, 0));
        boxCantidadMedianas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblComensales2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComensales2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cantidad de grandes.png"))); // NOI18N

        boxCantidadGrandes.setBorder(new LineBorder(new Color(221,188,0)));
        boxCantidadGrandes.setBackground(new java.awt.Color(255,243,163));
        boxCantidadGrandes.setBackground(new java.awt.Color(241, 228, 153));
        boxCantidadGrandes.setForeground(new java.awt.Color(0, 0, 0));
        boxCantidadGrandes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insertar.png"))); // NOI18N
        lblInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsertarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrar)
                .addContainerGap())
            .addComponent(lblSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComensales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxCantidadPequeñas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComensales1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxCantidadMedianas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComensales2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxCantidadGrandes, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCerrar)
                    .addComponent(lblAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblComensales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxCantidadPequeñas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblComensales1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxCantidadMedianas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblComensales2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxCantidadGrandes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(lblInsertar)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        // TODO add your handling code here:
        frmModulo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_lblCerrarMouseClicked
    
    private void lblInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertarMouseClicked
        // TODO add your handling code here:
        
        String seccion = boxSeccion.getSelectedItem().toString();
        int cantidadPequeñas = Integer.parseInt(boxCantidadPequeñas.getSelectedItem().toString());
        int cantidadMedianas = Integer.parseInt(boxCantidadMedianas.getSelectedItem().toString());
        int cantidadGrandes = Integer.parseInt(boxCantidadGrandes.getSelectedItem().toString());
        
        if(cantidadPequeñas == 0 && cantidadMedianas == 0 && cantidadGrandes == 0){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione al menos un tipo de mesa al que quieras insertar");
            return;
        }
        
        MesasAGuardarDTO mesasAGuardar = new MesasAGuardarDTO(seccion, cantidadPequeñas, cantidadMedianas, cantidadGrandes);
        
        mesaNegocio.guardarMesasEspecificadas(mesasAGuardar);
        
        JOptionPane.showMessageDialog(this, "Las mesas fueron insertadas correctamente");
        
    }//GEN-LAST:event_lblInsertarMouseClicked


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCantidadGrandes;
    private javax.swing.JComboBox<String> boxCantidadMedianas;
    private javax.swing.JComboBox<String> boxCantidadPequeñas;
    private javax.swing.JComboBox<String> boxSeccion;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblComensales;
    private javax.swing.JLabel lblComensales1;
    private javax.swing.JLabel lblComensales2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInsertar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
